from-the-storm/BORIS

frontend/global/global-styles.scss
frontend/global/normalize.scss
frontend/global/variables-mixins.scss
frontend/registration/registration.scss
frontend/registration/registration.tsx

I was planning to include a modified CSS reset at the end once all of the elements we're using are in place so I removed stuff like `margin: 0` from the `body` for now.

Minor changes to global and registration styles

---

frontend/lobby/lobby.scss
frontend/lobby/splash.tsx
frontend/registration/registration.scss

Tweak the splash to add a fade in

Sponsor splash

---

.circleci/config.yml
backend/backend-app.ts

This includes a CircleCI config file to run tests automatically on each PR.

Use CircleCI to run tests

---

frontend/app.tsx
frontend/global/actions.ts
frontend/global/state.ts
frontend/global/state/game-state-actions.ts
frontend/global/state/init-state-actions.ts
frontend/global/state/messages-state-actions.ts
frontend/global/state/messages-state.ts
frontend/main.tsx

Display errors in the UI when starting a game fails

---

backend/db/models.ts
backend/db/schema/001-initial-up.sql
backend/db/schema/dev-data.sql
backend/db/schema/test-data.sql
backend/game/manager.ts
backend/game/scripts/earthquake.yml
backend/game/scripts/group.yml
backend/game/scripts/land.yml
backend/game/scripts/water.yml

This change gives each of the four missions its own script, and also shows how the scripts can include common elements (to support the story).

Load a different script based on the scenario

---

backend/game/manager-test.ts
backend/game/manager.ts
backend/game/scripts/dev-script.yml
backend/game/scripts/earthquake.yml
backend/game/scripts/group.yml
backend/game/scripts/land.yml
backend/game/scripts/water.yml
backend/game/step.ts
backend/game/steps/choice-step-test.ts
backend/game/steps/choice-step.ts
backend/game/steps/loader.ts
backend/globals.d.ts
frontend/global/state/game-state.ts
package-lock.json
package.json

This allows steps in a script to run only if a certain condition is met, like `if team hasn't seen story 1 yet`.
An example is in the "Living off the Land" script: if you ask "Why 160", you'll see different messages from BORIS than if you don't.

Script conditions

---

backend/backend-app.ts
backend/db/db.ts
backend/db/migrate.ts
backend/db/schema/002-admin-users.sql
backend/db/schema/dev-data.sql
backend/routes/admin-api-test.ts
backend/routes/admin-api.ts
backend/routes/api-utils.ts

Only users whose ID is in the new `admin_users` table can see the admin or access the admin APIs.
Also fixes pagination of all the admin views.

Access control for the admin

---

frontend/game/ui-steps/message-step.tsx

Allow HTML in the messages from BORIS etc.

---

backend/game/steps/loader.ts
backend/game/steps/message-step.ts
backend/game/steps/pause-step-test.ts
backend/game/steps/pause-step.ts
common/game.ts
frontend/admin/scripts.tsx

A pause step pauses for the specified number of seconds.
Also cleans up some unused code.

Add a pause step

---

backend/game/manager.ts
backend/game/steps/bulletin.ts
backend/game/steps/free-response-step-test.ts
backend/game/steps/free-response-step.ts
backend/game/steps/loader.ts
common/game.ts
common/notifications.ts
frontend/admin/scripts.tsx
frontend/game/game.tsx
frontend/game/ui-steps/bulletin-step.tsx
frontend/game/ui-steps/choice-step.tsx
frontend/game/ui-steps/free-response-step.tsx
frontend/game/ui-steps/message-step.tsx
frontend/rpc-client/notifications.ts

Bulletin example:
Nameless org example:

Implement Bulletin & NO steps

---

backend/routes/admin-api-test.ts
backend/routes/admin-api.ts
frontend/admin/app.tsx
frontend/admin/scenarios.tsx

This allows creating and editing scenarios from the admin.
There is no delete functionality.

Create & Edit Scenarios in the Admin

---

frontend/registration/register.tsx

Fixes a minor bug during registration.

Fix: page didn't scroll to top when user clicks "I Consent"

---

backend/backend-app.ts
backend/db/redisClient.ts
backend/db/reset-db.ts
backend/websocket/online-users.ts
integration/integration-test.ts

- Reset redis before running test suite
- Use normal Chrome browser, not mobile emulation (buggy)

Improvements to tests

---

backend/routes/admin-api-test.ts
backend/routes/admin-api.ts
frontend/admin/teams.tsx

Useful in development, to test the same script again.

Helper tool to reset a team's variables

---

backend/game/steps/free-response-step-test.ts
backend/game/steps/free-response-step.ts
common/game.ts
frontend/admin/scripts.tsx
frontend/game/game.scss
frontend/game/ui-steps/free-response-step.tsx

Allow free responses to be restricted to a set of allowed values

---

backend/backend-app.ts
backend/checksum-test.ts
backend/checksum.ts
backend/config.ts
backend/views/react-app.pug
frontend/webpack.config.js
package-lock.json
package.json

* Add hash to URLs of main JS & CSS files to force them to reload when they've changed, and be cached otherwise.
* Minify JavaScript files in production (cut size by more than half)
* Use production build of React in production

Frontend optimizations

---

backend/game/manager-test.ts
backend/game/manager.ts

The main bug this fixes is that if the last step in a script has an `if` condition so it's only shown to some users, the game will end before those users see it.

Game engine fixes

---

backend/routes/login-register-test.ts
backend/routes/login-register.ts
common/api.ts
frontend/lobby/choose-scenario.tsx
frontend/lobby/lobby-state-actions.ts
frontend/lobby/lobby-state.ts
frontend/lobby/lobby.scss
frontend/lobby/lobby.tsx
frontend/lobby/pre-launch.tsx
frontend/lobby/team.tsx

Add a pre-launch screen to confirm that team members are online

---

frontend/game/game.scss
frontend/game/game.tsx
frontend/game/splash-boris-init.tsx
frontend/global/global-styles.scss
frontend/lobby/pre-launch.tsx
frontend/registration/join-team.tsx

@bradenmacdonald hey a couple things I forgot that need to be adjusted before the beta like the timing on the splash screen, the survey links removed from the team page, and some minor CSS stuff. Thanks so much!

Pre-beta adjustments

---

frontend/game/splash-boris-init.tsx

Increase time to finish BORIS animation

---

backend/backend-server.ts
backend/db/db.ts
backend/db/migrate.ts
backend/db/schema/integration-data.sql
frontend/game/game.tsx
frontend/game/ui-steps/choice-step.tsx
frontend/game/ui-steps/free-response-step.tsx
frontend/lobby/pre-launch.tsx
integration/integration-steps.ts
integration/integration-test.ts
integration/integration-utils.ts
integration/webdriver-utils.ts

This PR expands the automated integration tests to play through a partial script (as multiple users simultaneously) to provide verification for more of the game features.
It doesn't yet get as far as finishing a game. That will come in a future addition.
It also includes a couple miscellaneous fixes:
* Properly log certain errors when starting the server
* Don't play sounds if messages arrive while the splash screen is visible

A more complete integration test

---

backend/game/manager-test.ts
backend/game/manager.ts
backend/game/team-vars.ts

* `ELAPSED_MINUTES()` wasn't always working properly
* Setting a variable to `null` caused an error

Fix script JS bugs

---

backend/routes/admin-api-test.ts
backend/routes/admin-api.ts
backend/routes/lobby-api-test.ts
backend/routes/lobby-api.ts
common/api.ts
frontend/admin/data-provider.ts
frontend/admin/games.tsx
frontend/admin/teams.tsx
frontend/global/actions.ts
frontend/global/state.ts
frontend/global/state/leaders-state-actions.ts
frontend/global/state/leaders-state.ts
frontend/lobby/team.tsx
frontend/main.tsx

Implements leaderboards, showing the top ten teams.
Also:
* Allow easily viewing completed, abandoned, and active games in the Games admin
* Display time taken (minutes) for completed games in the admin
* Display team + scenario names in the Games admin
* List team members in the admin when viewing team details

Leaderboards

---

frontend/auto-wayfinder/auto-wayfinder.scss
frontend/auto-wayfinder/auto-wayfinder.tsx
frontend/lobby/choose-scenario.tsx
frontend/lobby/lobby.scss

Add scenario icons for Kelowna scenarios, adjust styles/zoom level of maps for better readability.

Minor style changes

---

backend/game/steps/loader.ts
backend/game/steps/map-step-test.ts
backend/game/steps/map-step.ts
backend/game/steps/progress-step-test.ts
backend/game/steps/progress-step.ts
common/game.ts
frontend/admin/app.tsx
frontend/admin/scripts.tsx
frontend/auto-wayfinder/auto-wayfinder.scss
frontend/auto-wayfinder/auto-wayfinder.tsx
frontend/auto-wayfinder/gmaps-constants.tsx
frontend/game/game.scss
frontend/game/game.tsx
frontend/game/ui-steps/map-step.tsx
frontend/game/ui-steps/progress-step.tsx
package-lock.json
package.json

```
- step: progress
percent: 38
message: You're <strong>38%</strong> of the way to the hidden reservoir! <strong><u>+5</u></strong> saltines.
```
Gives:
```
- step: map
message: You should be here
lat: 49.273164
lng: -123.102509
zoom: 16
```
Gives:

Progress & Map Steps

---

frontend/admin/data-provider.ts
frontend/admin/teams.tsx

@andrewmunroe This should fix the issues you had noticed:
* Couldn't "Show" a team in the admin
* When editing a Scenario, a warning message would appear at the bottom of the window.
This PR just makes some small changes required by the new `react-admin` version I switch to in #85.

Fix small admin bugs
