- backend/backend-app.ts
- backend/config.ts
- frontend/auto-wayfinder/auto-wayfinder.tsx
Adds Google Maps API Key
Disables SparkPost link rewriting.
Allows you to use a sparkpost API key locally by creating a folder called `boris-private` outside of the `boris` folder (next to it) and putting e.g. `sparkpost_api_key: 234567...` in a file called `dev-config.yml`
> Google Maps API Key + Better SparkPost Usage

- .circleci/config.yml
This will automatically update [the docker image of BORIS on Docker Hub](https://hub.docker.com/r/fromthestorm/boris/tags/) when we push to the `beta` branch.
Next step will be to automatically update the live server too.
> Build Docker image of BORIS using CircleCI

- deploy/roles/app/defaults/main.yml
- deploy/roles/app/meta/main.yml
- deploy/roles/app/tasks/main.yml
- deploy/roles/app/templates/docker-compose.yml.j2
- deploy/roles/docker-ansible/tasks/main.yml
- deploy/roles/traefik-load-balancer/defaults/main.yml
- deploy/roles/traefik-load-balancer/meta/main.yml
- deploy/roles/traefik-load-balancer/tasks/main.yml
- deploy/roles/traefik-load-balancer/templates/docker-compose.yml.j2
- deploy/roles/traefik-load-balancer/templates/traefik.toml.j2
This uses Træfik to get a Let's Encrypt HTTPS certificate, so we don't need to rely on CloudFlare HTTPS. This prevents unencrypted data from passing between Cloudflare's servers (which could be outside of Canada) and our Toronto servers.
> Deploy using Traefik for HTTPS + proxying

- backend/config.ts
- backend/test-lib/utils.ts
- backend/websocket/connections-test.ts
- backend/websocket/connections.ts
If a user had two websockets open and closed one, they'd appear offline for ~1 min.
Also fixes an issue where the tests weren't using an isolated redis prefix.
> Fix minor bug when a user has multiple simultaneous connections

- backend/routes/admin-api-test.ts
- backend/routes/game-api.ts
- common/api.ts
- frontend/global/state/game-state-actions.ts
- frontend/rpc-client/manager.ts
If anything about the game changed while a phone is asleep or not connected, the phone would not update correctly when woken up. This fixes that by explicitly checking the state of the game with the server whenever a websocket connection is reestablished.
> Update game state on disconnect

- backend/backend-app.ts
- backend/db/schema/test-data.sql
- backend/game/manager.ts
- backend/game/script-loader-test.ts
- backend/game/script-loader.ts
- backend/game/steps/award-saltines-integration-test.ts
- backend/game/steps/award-saltines.ts
- backend/game/steps/loader.ts
- backend/routes/market-api.ts
- common/api.ts
- frontend/admin/scripts.tsx
- frontend/global/state/team-state-actions.ts
- frontend/global/state/team-state.ts
- frontend/lobby/team.tsx
This adds a step that can award saltines.
This displays the current amount of saltines for the team in the team info page.
This also adds a new `if`/`elif`/`then` syntax which makes writing scripts much easier. Behind the scenes, these get rewritten to use `goto` and `target` steps.
Example script:
```
- step: message
messages:
- Hello from BORIS! This script will award your team some saltines.
- Do you want some saltines?
- step: choice
key: wantsSaltines
correct: yes
choices:
- yes: Yes
- no: No
- if: VAR('wantsSaltines') === 'yes'
then:
- step: message
messages:
- Ok, awarding you 3 saltines
- step: award
earned: 3
possible: 3
- else:
then:
- step: message
messages:
- Ok, awarding you 0 saltines
- step: award
earned: 0
possible: 3
- step: pause
for: 2
```
> Step that can award saltines

- backend/db/schema/test-data.sql
- backend/game/manager.ts
- backend/game/step.ts
- backend/game/steps/loader.ts
- backend/game/steps/message-step-test.ts
- backend/game/steps/message-step.ts
- backend/game/steps/set-step-integration-test.ts
- backend/game/steps/set-step.ts
- backend/routes/admin-api-test.ts
- backend/routes/admin-api.ts
- backend/test-lib/mock-game-manager.ts
- frontend/admin/app.tsx
- frontend/admin/scripts.tsx
- frontend/admin/teams.tsx
Here is a script that tests these features:
```yaml
- step: message
messages:
- Hello from BORIS!
- ['"You have played this scenario " + VAR("num_times_played", 0) + " times"']
- step: set
scope: team
key: num_times_played
to: VAR('num_times_played', 0) + 1
- step: choice
key: chooseXtoEndGame
choices:
- x: Cool
```
> Set variables from scripts, use variables in messages

- integration/interactive-multisession.ts
- package.json
This adds a little helper script that you can use to login as 2-5 separate users to test scripts.
Usage example:
```
npm run interactive-multisession 4 http://localhost:3333
```
> Helper to launch 2-5 separate browsers

- package-lock.json
- package.json
This fixes a bug in #50 which caused it to not work in production, since it cannot detect the version of React being used when React is not installed.
It also fixes a bug caused by json-rpc-peer installing a new version of the babel runtime that has breaking changes.
> Fix: React version detection requires react to be installed in prod builds

- backend/game/manager.ts
- backend/game/steps/award-saltines.ts
- backend/game/steps/set-step.ts
- backend/routes/admin-api.ts
This fixes a bug whereby saltines were not being awarded in some cases.
This also makes inactive scenarios appear in the admin, so that they can be reactivated.
> Fix: Sometimes saltines were not being awarded correctly

- backend/routes/login-register.ts
- backend/routes/login-template.html
Since some people couldn't use their default browser and didn't know how to copy a link's address on their mobile device.
> Include the full URL of the login link in plain text

- backend/routes/market-api.ts
- common/api.ts
- frontend/global/state/team-state.ts
Fix:
> After a team has completed 3 scenarios, the 'actualized' graphic should show - which it does. But at that point the Burdened should still be able to enter the market. Currently they can't.
>
> Then after a 4th scenario, no users should be allowed to enter the market - it should be boarded up or taped or whatever.
> Fix behavior of Actualized market status

- frontend/game/game.scss
- frontend/lobby/choose-scenario.tsx
- frontend/lobby/lobby.tsx
- frontend/lobby/pre-launch.tsx
- frontend/lobby/team.tsx
- frontend/prompt/prompt.scss
- frontend/registration/register.tsx
@bradenmacdonald After testing it out I think the initial post-registration survey prompt should open in the same window. Currently if a user goes through the survey and submits it, they get automatically redirected back to the game. And then the game is running in two windows, which users may not realize. 
The disadvantage with this is that people may abandon the survey and not know how to get back... or think that the survey is a mandatory part of registering. But with this update hopefully in making it not open fullscreen and tweaking the language will help with that.
> UI updates

- frontend/registration/home.tsx
This adds a link here so that if anyone ends up on the `play` site without knowing what this is about, they can find the main site.
> Provide a link from the app to the marketing site

- backend/db/migrate.ts
- backend/db/models.ts
- backend/db/schema/004-scenario-city.sql
- backend/db/schema/test-data.sql
- backend/routes/admin-api-test.ts
- backend/routes/admin-api.ts
- common/models.ts
- frontend/admin/scenarios.tsx
- frontend/lobby/choose-scenario.tsx
- frontend/lobby/lobby.scss
- frontend/lobby/team.tsx
Switching tabs shows/hides scenarios with CSS based on the `.scenario-choice` IDs, which maybe isn't ideal. Should there instead be a new database column to specify a scenario's city?
> Add tabs to switch cities

- backend/routes/admin-api-test.ts
- backend/routes/admin-api.ts
- backend/routes/api-utils.ts
- backend/test-lib/utils.ts
- common/api.ts
- frontend/admin/app.tsx
- frontend/admin/scripts.tsx
- frontend/admin/teams.tsx
- frontend/admin/users.tsx
Allows admin users to delete teams, scenarios, and scripts from the admin.
Note: it doesn't prompt to ask you to confirm, but it does let you undo the delete if you click "Undo" near the bottom of the screen within a few seconds of having clicked delete.
> Allow deleting things from the admin

- backend/websocket/connections.ts
- frontend/lobby/choose-scenario.tsx
- frontend/lobby/lobby.tsx
This fixes a bug introduced in #79, which causes any user to appear to be offline after 60s, even though the connection is kept open and they're still online.
It also improves the lobby UI by scrolling to the top of the screen whenever the user changes to a new page.
> User online status fix

- backend/views/react-app.pug
Hi @bradenmacdonald we're wanting to add GTM to track conversions from the marketing campaign. This seemed to work on lobby screens but I couldn't start the game locally because the scenarios don't show up on the **Choose Scenario** screen.
I assume because they need to be assigned to a city, but when I try to do that in the admin I get this error: `Error: column "city" of relation "scenarios" does not exist`. I tried resetting the db but still same issue.
> Add Google Tag Manager to app

- backend/db/migrate.ts
- backend/db/models.ts
- backend/db/schema/005-scenario-order.sql
- backend/db/schema/test-data.sql
- backend/routes/admin-api-test.ts
- backend/routes/admin-api.ts
- backend/routes/lobby-api.ts
- common/models.ts
- frontend/admin/scenarios.tsx
This adds a new "Order" field for each scenario in the admin which can be used to adjust the order in which they appear. If two scenarios have the same Order number, they'll be sorted alphabetically.
Once you check this branch out, in VS Code you must go Tasks > Run Task > Apply Database Migrations.
> Sort scenarios by specified order

- frontend/lobby/team.tsx
Current headers cause horizontal scroll on most devices
> Shorten leaderboard headers
